Made catch error cog and make cog management system.
lpdf/0w0nator pull request #10
Opened 2021-07-04 06:48 UTC by TNTprizz

2021-07-05 13:06 UTC, windowsboy111 commented
I feel like we need to rename config.yml to config.yml.example or sth similar

2021-07-05 13:08 UTC, TNTprizz commented
Winboi:
> 
> I feel like we need to rename config.yml to config.yml.example or sth similar

No need cuz no one knows that touching `config.yml` is essential for the bot to run
just config.yml ok, no need example

2021-07-05 13:14 UTC, windowsboy111 requested changes

2021-07-05 13:14 UTC, windowsboy111 commented on src/bot.py
> +intents = discord.Intents().all()
`discord.Intents.all()`

2021-07-05 13:14 UTC, windowsboy111 commented on src/cogs/Bash.py
> +                except:
maybe `except Exception:`

2021-07-05 13:14 UTC, windowsboy111 commented on src/cogs/Vote.py
> +mvotelist = ["🇦","🇧","🇨","🇩","🇪","🇫","🇬","🇭","🇮","🇯","🇰","🇱","🇲","🇳","🇴","🇵","🇶","🇷","🇸","🇹"]
make them a str, not list. see `wb/patch`.
Same goes for `tfvotelist`.

2021-07-05 13:14 UTC, windowsboy111 commented on src/cogs/Vote.py
> +    bot.mvote = {}
See `wb/patch`

2021-07-05 13:14 UTC, windowsboy111 commented on src/cogs/error.py
> +        if isinstance(error, commands.MissingPermissions) or isinstance(error, commands.MissingRole) or isinstance(error, commands.MissingAnyRole):
`if isinstance(error, (commands.MissingPermissions, commands.MissingRole, commands.MissingAnyRole)):`

2021-07-05 13:15 UTC, TNTprizz commented on src/bot.py
> +intents = discord.Intents().all()
don't work if no Intents`()`

2021-07-05 13:15 UTC, TNTprizz commented on src/cogs/Bash.py
> +                except:
same la but I will change it

2021-07-05 13:16 UTC, TNTprizz commented on src/cogs/Vote.py
> +mvotelist = ["🇦","🇧","🇨","🇩","🇪","🇫","🇬","🇭","🇮","🇯","🇰","🇱","🇲","🇳","🇴","🇵","🇶","🇷","🇸","🇹"]
ahh ok

2021-07-05 13:16 UTC, windowsboy111 commented
1. Understand that cogs and extensions are different.
2. you don't always need `bot`.
3. pro tip: `contextlib.suppress()`
4. strings can be indexed.

2021-07-05 13:23 UTC, TNTprizz commented on src/bot.py
> +intents = discord.Intents().all()
whoops sor

2021-07-05 13:26 UTC, TNTprizz commented on src/cogs/Vote.py
> +    bot.mvote = {}
what is in `wb/patch`

2021-07-05 13:30 UTC, TNTprizz commented
> 
> 
>     1. Understand that cogs and extensions are different.
> 
>     2. you don't always need `bot`.
> 
>     3. pro tip: `contextlib.suppress()`
> 
>     4. strings can be indexed.

1. So, what we need is a extension directory
2. My goal is to reach the goal
3. Pro tip: I am noob
4. This is right, but the regional indicator sticks together when not using list and that is...... just annoying

2021-07-19 04:00 UTC, windowsboy111 commented
Merged with #8.

2021-07-19 04:00 UTC, closed without merging